# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: docker-build
author: Release Engineering <rel-eng@hashicorp.com>
description: Builds and stores Docker images.

inputs:

  # Required explicit inputs.
  version:
    description: Version of the product, e.g. "X.Y.Z[-pre][+edition]".
    required: true

  arch:
    description: Target image architecture.
    required: true

  revision:
    description: >
      Full sha of the commit that is being built.
      This may differ from the default <github.sha> which is the ref the action
      was invoked at.
    default: "${{ github.sha }}"

  tags:
    description: >
      Whitespace-separated fully-qualified image names to use for production releases.
      If you set tags non-empty, then the redhat_tag input must be empty.
      Each tag must be in the format: <registry>/[<namespace>/]<repository>:<tag>
    default: ""

  redhat_tag:
    description: >
      Single tag to use for pushing to Red Hat Certified Container Project.
      If you set redhat_tag non-empty, then the tags input must be empty.
      Each tag must be in the format: <registry>/[<namespace>/]<repository>:<tag>
    default: ""

  # General purpose inputs.
  target:
    description: >
      Dockerfile target stage to build.
      You should set this explicitly if your Dockerfile contains more than one target.
      You should use the target name (i.e. FROM ... AS <target name>) not the index.
      Defaults to 0, meaning the first target defined (fine if only one target).
    default: "0"

  arm_version:
    description: Version of arm architecture to use (ignored unless arch == arm).
    default: 6

  smoke_test:
    description: >
      Bash shell script to run as a smoke test against the built image.
      Inside the script, you will have access to a variable called 'IMAGE_NAME'
      which you can use in your test to run the image. The script currently only
      run against the `linux/amd64` build and will have access to a local docker
      daemon. Tests should not be specific to `amd64` arch nor rely on the daemon
      being local as these may change later to enable testing to all other images.
      The script must exit non-zero in order to mark the test as failed.
    required: false
    default: ""

  # Optional inputs whose values are guessed if left blank.
  zip_artifact_name:
    description: >
      Name of zip file artifact to download. If left empty defaults to
      ${PKG_NAME}_${OS}_${ARCH}.zip.
    default: ""

  pkg_name:
    description: >
      Only used to determine default zip name.
      Defaults to <repo-name(minus -enterprise)>_<version>[+ent]
      if left blank.
    default: ""

  bin_name:
    description: >
      Name of the product binary inside the zip file. If empty (which is the default)
      then the name is guessed using repo name with any -enteprise suffix removed.
    default: ""

  # Set defaults in scripts/digest_inputs.sh
  dev_tags:
    description: Tags to use for publishing development images (optional).
    default: ""

  push_auto_dev_tags:
    description: Tag to determine whether to push default dev tags (optional).
    default: "false"

  # Escape hatch inputs (use sparingly if at all).
  workdir:
    description: Working directory in which to run 'docker build'.
    default: .

  dockerfile:
    description: Dockerfile path relative to workdir.
    default: Dockerfile

  do_zip_extract_step:
    description: Should zip archives be extracted? (optional)
    default: true
    type: boolean

# action runner (golang:latest image)
runs:
  using: composite
  #env:
  #  DOCKER_BUILDKIT: 1
  #  BUILDKIT_PROGRESS: plain
  steps:
    - name: Set required repo name env var
      shell: bash
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -f2 -d "/")" >> $GITHUB_ENV

    - name: Digest Inputs - Calculate Variables for Later Steps
      shell: bash
      env:

        # Required.
        REVISION: "${{ inputs.revision }}"
        VERSION: "${{ inputs.version }}"
        ARCH: "${{ inputs.arch }}"
        TAGS: "${{ inputs.tags }}"
        REDHAT_TAG: "${{ inputs.redhat_tag }}"
        TARGET: "${{ inputs.target }}"

        # Optional.
        DEV_TAGS: "${{ inputs.dev_tags }}"
        PUSH_AUTO_DEV_TAGS: "${{ inputs.push_auto_dev_tags }}"
        ARM_VERSION: "${{ inputs.arm_version }}"
        PKG_NAME: "${{ inputs.pkg_name }}"
        WORKDIR: "${{ inputs.workdir }}"
        ZIP_NAME: "${{ inputs.zip_artifact_name }}"
        BIN_NAME: "${{ inputs.bin_name }}"

        DOCKERFILE: "${{ inputs.dockerfile }}"

      run: $GITHUB_ACTION_PATH/scripts/digest_inputs

    - name: Setup QEMU in binfmt_misc filesystem
      shell: bash
      run: ${{ github.action_path }}/scripts/register_qemu_binfmt

    - name: Download Product Zip Artifact
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      if: ${{ inputs.do_zip_extract_step == 'true'  }}
      with:
        path: ${{ env.ZIP_LOCATION }}
        name: ${{ env.ZIP_NAME }}

    - name: Extract Product Zip Artifact
      if: ${{ inputs.do_zip_extract_step == 'true' }}
      shell: bash
      run: ${{ github.action_path }}/scripts/extract_product_zip

    - name: Docker Build
      shell: bash
      run: ${{ github.action_path}}/scripts/docker_build

    - name: Run Test
      if: ${{ env.PLATFORM == 'linux/amd64' && inputs.smoke_test != '' }}
      shell: bash
      run: ${{ inputs.smoke_test }}
      env:
        IMAGE_NAME: ${{env.AUTO_TAG}}

    - name: Generate Docker metadata
      shell: bash
      run: ${{ github.action_path}}/scripts/create_metadata

    - name: Upload Docker Image metadata
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      env:
        # Add _redhat if this is a redhat call.
        REDHAT_SUFFIX: ${{ inputs.redhat_tag && '_redhat' || '' }}
      with:
        name: docker_tag_list_${{env.TARGET}}${{env.REDHAT_SUFFIX}}.json
        path: docker_tag_list_${{env.TARGET}}${{env.REDHAT_SUFFIX}}.json
        if-no-files-found: error

    - name: Upload Prod Tarball
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: ${{ env.TAGS != '' }}
      with:
        name: ${{ env.TARBALL_NAME }}
        path: ${{ env.TARBALL_NAME }}
        if-no-files-found: error

    - name: Upload Dev Tarball
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: ${{ env.DEV_TAGS != '' }}
      with:
        name: ${{ env.DEV_TARBALL_NAME }}
        path: ${{ env.DEV_TARBALL_NAME }}
        if-no-files-found: error

    - name: Upload Red Hat Tarball
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: ${{ env.REDHAT_TAG != '' }}
      with:
        name: ${{ env.REDHAT_TARBALL_NAME }}
        path: ${{ env.REDHAT_TARBALL_NAME }}
        if-no-files-found: error
