#!/usr/bin/env bash

set -Eeuo pipefail

#Check if DEV_TAGS is unset, if not
if [ -z "${DEV_TAGS:-}" ]; then
    DEV_TAGS=""
fi
jq --null-input --arg tags "${TAGS}" \
    --arg dev_tags "${DEV_TAGS}" \
    '{
        tags: $tags | split("\n")[:-1],
        dev_tags: $dev_tags | split("\n")[:-1]
    }' >> docker_tag_list_"${TARGET}".json
