#!/usr/bin/env bash

set -Eeuo pipefail


if [ -z "${DEV_TAGS+x}" ]; then
    jq --null-input --arg tags "${TAGS}" \
    '{
        tags: $tags | split("\n")
    }' >> docker_tag_list_"${TARGET}".json

    echo $PWD
else
   jq --null-input --arg tags "${TAGS}" \
    --arg dev_tags "${DEV_TAGS}" \
    '{
        tags: $tags | split("\n"),
        dev_tags: $dev_tags | split("\n")
    }' >> docker_tag_list_"${TARGET}".json

    echo $PWD
fi
