#!/usr/bin/env bash

set -Eeuo pipefail

echo "==> Registering qemu into /proc/sys/fs/binfmt_misc"
docker run --pull always \
           --privileged \
           --rm \
           docker.mirror.hashicorp.services/tonistiigi/binfmt:qemu-v9.2.2 --install all
